spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: database
  redis:
    host: 127.0.0.1
    port: 6379
  application:
    name: mongoAndJWT
eureka:
    client:
       service-url:
           defaultZone: http://127.0.0.1:1008/eureka/
    instance:
      prefer-ip-address: true #开启微服务可跨域访问
jwt:
  config:
    key: HeavenY    #加盐
    ttl: 3600000    #过期时间1个小时
server:
  port: 8081